language: java

jdk:
- oraclejdk7

install: 'mvn dependency:resolve -U'

script: 'mvn clean install deploy --settings src/main/config/travis-maven-settings.xml'

env:
  global:
  - secure: p7kjJsbFhLWHHMQM36BLU440phmcv7LBJlzx0WIsKFUUM8KAjKoCUgHhwhJP0eNyk/p87Obb9SXzndJljNPpThIszjBEWJfdAqOQ86p6Q9+ayWwp/yQsHhVKPEgWCGPTcH4jx1LpNxCkTZZ4D1i6jAqcI450GiTP0hMQfMXLOpA=
  - secure: hlnfafsCp5EEEQHTRZcQnDPVyYprzUPDB9pfNs8WOTJDW4VyJzdGxRIJV261SRCpcK8N+bEhrQtHa9D9MWi6pMZO1g7RmKrQ0mxX/RV2rmaszuNiyLGhrKlHxoYiX2zYh8uI1CSQt+P/3eEyht4gfCL7OdtaLsrQ0rr2Nh4OpEM=
